)BODY
%&ZPRODTSK CHANGES /ฤ/ OPTIONAL MVS ACCESS /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD / /+
+
+  This optional program offers full transparent access to all
+  mainframe files and status via LU2 or LU6.2 and HLLAPI.
+
+  *-----------------------------------------------------------*
+  * Shipping 4th Quarter, 1994. Call (800) 336-3320 for info  *
+  *-----------------------------------------------------------*
)PROC
&ZSEL = "UP"
)END
