)BODY
%&ZPRODTSK CHANGES /ฤ/ PRINT SETUP ENHANCEMENTS /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD/ /+
+
+  Print Setup Options Panel 0.2 has been enhanced to provide the
+  following new features:
+
+     * page width now specifiable
+
+     * right margin now specifiable
+
+     * header/footer alignment now specifiable
+
+  For further details see:
+
+     SPF/PC User Guide and Reference,
+        Printer Characteristics ......... Page 9-6
)PROC
&ZSEL = "UP"
)END
