)BODY
%&ZPRODTSK CHANGES /ฤ/ OPTIONAL XDB INTERFACE /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD / /+
+
+  This feature emulates the "DB2 Interactive" primary option of ISPF
+  and works in conjunction with XDB, the PC based DB/2.
+
+  *-----------------------------------------------------------*
+  * Shipping 4th Quarter, 1994. Call (800) 336-3320 for info  *
+  *-----------------------------------------------------------*
)PROC
&ZSEL = "UP"
)END
