)body
%&ZPRODTSK /ฤ/ BROWSE ฤ ENTRY PANEL /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD / /%
+
+PROJECT FILE:
+   DRIVE%อออ_Z +
+   PATH %อออ$ZFPATH1                                                         +
+   PATH %อออ$ZFPATH2                                                         +
+   PATH %อออ$ZFPATH3                                                         +
+   NAME %อออ$ZFNAME                                                          +
+              (Blank or pattern for file selection list)
+
+SYSTEM CUR DIR:%&ZCURDIR                                                      +
+
+SYSTEM FILE SPECIFICATION:
%อออ$ZFSPEC                                                                   +
+
+PROFILE %อออ_ZPROF   + (Blank defaults to file extension)
+
)init
.ZVARS = "ZFDRIVE"
.HELP  = "S2R10000"
)proc
)end
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
