)ATTR
   '^' TYPE(PROT) ATTN(ON) INTENS(HIGH)
)body
%&ZPRODTSK /ฤ/ CONFIRM DELETE /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD / /%
+
+FILE:%&fpath                                                                  +
+
+INSTRUCTIONS:
+   Press^ENTER+key to confirm delete request.
+   Enter^END+command to cancel delete request.
)init
)proc
)end

(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
