)body
%&ZPRODTSK /ฤ/ COPY FILE /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD / /%
+
+CURRENT DIR:%&ZcurDir                                                         +
+
+SOURCE FILE:%&fpath                                                           +
+
+TARGET FILE:
+   NAME%อออ$ToName                                                           +
+
)init
)proc
)end
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
