)ATTR
 # Type(OUTPUT) Intens(High)
)body
%&ZPRODTSK /ฤ/ &ZTITLE /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD / /%SCROLL อออ_Z   %
%&ZCURDIR
%    NAME                                               SIZE      DATE
%/ฤ/
)MODEL
_Z +#NAMESHRT                                        #CSIZE    #CDATE
)INIT
&ZTDMARK = "        &ZDTFILES  &ZDTBYTES BYTES USED -- END OF FILE SELECTION LIST"
.ZVARS = "SCROLL SEL"
)END
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
