)ATTR
   '~' TYPE(OUTPUT) INTENS(LOW)
)body
%&ZPRODTSK /ฤ/ &KBETITLE /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD / /%SCROLL อออ_Z   %
+
+       %NEW+- Create new custom key definition
+
+%NAME:~ZKBNAME + %DESCRIPTION: ~ZKBDESC                                      +
+
%  NAME                            VALUE
%/ฤ/
)MODEL
_Z~EVTNAME                        ~EVTVALUE
)INIT
.ZVARS = "SCROLL SEL"
)END
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
