)ATTR
   "^" TYPE(PROT) INTENS(HIGH) ATTN(ON)
)BODY
%&ZPRODTSK /ฤ/ INTERACTIVE MACRO RECORDER /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD / /%
+
+ MACRO NAME        %อออ_MACNAME +
+ MACRO DESCRIPTION %อออ_MACDESC                                              +
+
+    PRESS^END+TO COMPLETE THE DEFINITION AND BEGIN MACRO RECORDING.
+    ENTER^CANCEL+TO ABORT MACRO.
+
)DISP
)PROC
VER ( &MACNAME, NB )
)END
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
