)ATTR
   '~' TYPE(OUTPUT) INTENS(LOW)
)body
%&ZPRODTSK /ฤ/ &KBETITLE /ฤ/ %V &ZSHRTVER
%COMMAND อออ$ZCMD / /%SCROLL อออ_Z   %
+
+NAME:~ZKBNAME + DESCRIPTION:~ZKBDESC                                         +
+
%NAME                   VALUE
%/ฤ/
)MODEL
~EVTNAME               _EVTVALUE                                               %
)INIT
.ZVARS = "SCROLL"
)END
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
