)ATTR
   '^' TYPE(PROT) ATTN(ON) INTENS(HIGH)
)body
%&ZPRODTSK /ฤ/ SAVE LIST /ฤ/ V &ZSHRTVER
%COMMAND อออ$zcmd / /+
+
+   LIST NAME  %อออ_lname   +
+
+   DESCRIPTION%อออ_ldesc                                                     +
+
+
+   Press^ENTER+key to save the list.
+   Enter^END+command to cancel.
)init
.HELP   = "S2R3F000"
)proc
)end
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
