)attr
  '^' TYPE(INPUT) SCROLL(ON) CAPS(OFF) JUST(ASIS) INTENS(HIGH)
)body
%&ZPRODTSK /ฤ/ FILE LIST SEARCH UTILITY /ฤ/ V &ZSHRTVER
%COMMAND อออ$zcmd / /%
+
+   Enter one or more search arguments:
+
+   ASIS%อออ^ARG0                                                             +
+   ASIS%อออ^ARG1                                                             +
+   ASIS%อออ^ARG2                                                             +
+   ASIS%อออ^ARG3                                                             +
+
+   CAPS%อออ^ARG4                                                             +
+   CAPS%อออ^ARG5                                                             +
+   CAPS%อออ^ARG6                                                             +
+   CAPS%อออ^ARG7                                                             +
+
+
+   Membership in the inclusion set is determined by a match on ANY string
)init
)proc
)end
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
