)body
%&ZPRODTSK /ฤ/ CONCURRENT LICENCE ERROR /ฤ/ V &ZSHRTVER
%COMMAND อออ&ZCMD / /%
+
+  MESSAGE: %&Zmuerr1                                                          +
+           %&Zmuerr2                                                          +
+           %&Zmuerr3                                                          +
+
+
+  Press any key to return.
)init
)proc
)end
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
