)BODY
%&ZPRODTSK HELP /ฤ/ SCROLL AMOUNT /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD                                                             +
+
+   %SCROLL อออ csr+    or %SCROLL อออ c+   ฤ  to scroll to the position
+                                                of the cursor within the
+                                                data (or by a page if the
+                                                cursor is outside the data
+                                                or is already positioned
+                                                in the top, bottom, left,
+                                                or right margin).
+
+   %SCROLL อออ max+    or %SCROLL อออ m +  ฤ  to scroll to the top,
+                                                bottom, left, or right
+                                                margin.
+
+   %SCROLL อออ data+   or %SCROLL อออ d +  ฤ  to scroll by a page minus
+                                                one line when scrolling up
+                                                or down or by a page minus
+                                                one column when scrolling
+                                                left or right.
+
+
+
+                           (Press%ENTER+to continue)
)PROC
)END
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
