)BODY
%&ZPRODTSK HELP /ฤ/ SCROLL AMOUNT /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD                                                             +
+
+  Panels which support scrolling normally display the scroll amount value
+  in the header line, following the COMMAND/OPTION field.
+
+  You can change the scroll amount by overtyping the scroll amount field
+  with a new value.  If%MAX+or%M+is entered, the previous value is restored
+  following the scroll operation.  If any other scroll amount is entered, it
+  remains in effect until you change it or until you begin a new function.
+  Valid scroll amounts are:
+
+   %SCROLL อออ page+   or %SCROLL อออ p+   ฤ to scroll by one page.
+
+   %SCROLL อออ half+   or %SCROLL อออ h+   ฤ to scroll by half a page.
+
+   %SCROLL อออ 1+      or %SCROLL อออ 50+  ฤ or any number from 1 to 9999
+                                               to scroll by the specified
+                                               number of lines.
+
+
+
+
+                           (Press%ENTER+to continue)
)PROC
)END
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
