)BODY
%&ZPRODTSK HELP /ฤ/ PATHS PANEL /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD                                                             +
+
+  The search for control files proceeds in the following directory order:
+
+    applicable custom path, if not found , then
+
+    applicable preset path, if not found , then
+
+    default search path, if not found , then
+
+    executable path, if not found , then
+
+    current directory
+
+
+
+
+
+
+
+
+
+                     (Hit%ENTER+to return to previous menu)
)PROC
)END
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
