)BODY
%&ZPRODTSK HELP /Ä/ DATA ENTRY PANELS /Ä/ V &ZSHRTVER
%COMMAND ÍÍÍ$ZCMD                                                             +
+
+  Data entry panels allow you to specify information such as data set
+  names, or operating system commands.  The fields in which you may enter
+  information are labeled and preceded with an arrow.  If you do not enter
+  a required value or if you enter inconsistent values, you will be
+  prompted with a message.
+                              ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
+  The example at the right    ³%SPF/PC(1) ÄÄÄÄÄÄÄÄÄÄÄ BROWSE Ä ENTRY PANEL+
+  shows part of the browse    ³%COMMAND ÍÍÍ+
+  filename data entry panel.  ³
+                              ³ PROJECT FILE:
+                              ³   DRIVE  %ÍÍÍ+F
+                              ³   PATH   %ÍÍÍ+\COBOL
+                              ³   PATH   %ÍÍÍ+
+                              ³   PATH   %ÍÍÍ+
+                              ³   NAME   %ÍÍÍ+AP50CTC.COB
+
+
+
+
+
+                           (Press%ENTER+to continue)
)PROC
)END
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
