)BODY
%&ZPRODTSK HELP /ฤ/ DIALOG TEST /ฤ/ V &ZSHRTVER
%COMMAND อออ$ZCMD                                                             +
+
+  %TESTING TABLES+
+
+          In the normal course of dialog development, tables are created,
+          modified and and displayed in panels. To display or alter a table,
+          select Dialog Test Option 3.
+
+          Table Test presents a select list of all disk-based tables. Tables
           which are created with the NOWRITE option are not displayed in the select list.
+          With Table Test you can:
+
+             Edit a table using the 'E' line command.
+
+             Copy the table using the 'C' line command.
+
+             Delete the table using the 'D' line command.
+
+             Rename the table using the 'R' line command.
+
+
+
+                          (Press%ENTER+for next page)
)PROC
)END
(C) Copyright 1984-1994, Command Technology Corporation.  All Rights Reserved.
